# Generated by Django 4.0.4 on 2022-05-01 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 1, 14, 30, 37, 592564, tzinfo=utc)),
        ),
    ]
