# Generated by Django 4.0.4 on 2022-05-01 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userincome',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='userincome',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 1, 14, 30, 37, 596564, tzinfo=utc)),
        ),
    ]
